apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
   app: workflow-api
  name: workflow-api
  namespace: workflow-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workflow-api
  template:
    metadata:
      labels:
        app: workflow-api
    spec:
