commonLabels:
  env: dev
commonAnnotations:
  note: This is a dev environment
resources:
  - ../../base
patches:
  - path: deployment.yaml
  - path: namespace.yaml
  - path: service.yaml 
  - path: virtual-service.yaml
