# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  teste: 
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Configurar Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: instalar dependencias
        run: pip install -r requirements.txt
      - name: Testando
        run: pytest
  lint:
    runs-on: ubunto-latest
    needs: teste
    steps:
      - uses: actions/checkout@v3
      - name: configurar python
        uses: actions/setup-python@v4 
        with: 
          python-version: 3.9
      - name: instalar dependencias
        run: pip install -r requirements.txt
      - name: Rodar analise
        run: pylint my_module.py
